apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-app-old
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Test project to delete

  sourceRepos:
    - '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc