apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app-new
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  project: root-app-new

  source:
    repoURL: https://github.com/vanny96/argocd-branches
    path: new-way/envs/prod
    targetRevision: prod
