apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-old
spec:
  destination:
    namespace: goldenalgo
    server: https://kubernetes.default.svc
  project: root-app
  source:
    repoURL: ghcr.io/vanny96
    chart: helloworld-helm
