apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-old
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-environment
  project: root-app-old
  source:
    repoURL: ghcr.io/vanny96
    chart: helloworld-helm

  syncPolicy:
    syncOptions:
      - CreateNamespace=true