apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-old
  namespace: argocd
spec:
  source:
    targetRevision: 2.0.0
    helm:
      parameters:
        - name: helloworld.environment
          value: dev